# Generated by Django 4.0.2 on 2022-02-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_gear_alter_fish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pines', 'Lake O The Pines'), ('Caddo', 'Caddo Lake'), ('Lone Star', 'Lake Lone Star'), ('Sandlin', 'Lake Bob Sandlin')], default='Pines', max_length=100)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fish')),
            ],
        ),
    ]
