# Generated by Django 4.0.2 on 2022-02-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_lake'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='gears',
            field=models.ManyToManyField(to='main_app.Gear'),
        ),
    ]
