# Generated by Django 4.0.2 on 2022-02-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_log_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='location',
            new_name='name',
        ),
    ]
