# Generated by Django 4.0.2 on 2022-02-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_location_log_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='name',
            new_name='location',
        ),
    ]
