# Generated by Django 4.0.2 on 2022-02-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_gear_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='user',
        ),
    ]
